### ISSUE TITLE
hotfix preview

### ISSUE THREAD

**Issue by Joao-Pedro-P-Holanda** [gustavohenriquefs/SGEC#115]
## Todos os previews
- [x]  Adicionar efeito `drop shadow`

---

### PreviewEventoExistente

- [x]  Reduzir comprimento para menos do que a altura
- [x]  Fazer ImageView ocupar uma porcentagem maior da tela
- [x] Adicionar efeito de zoom on hover, testar com fx-scale:
```css
.component:hover{
-fx-scale-x : 1.1;
-fx-scale-y : 1.1;
-fx-scale-z: 1.1;
}
```
---
### PreviewInstituicao

- [x] Mudar layout para a vertical, com ImageView à esquerda e Labels à direita
- [x] Adicionar Label com nome da instituição abaixo da ImageView
- [x] Diminuir ambas as dimensões proporcionalmente
- [x] Reduzir espessura das bordas ou utilizar outra cor

--- 
### PreviewParticipante

- [x] Diminuir comprimento
- [x] Fazer ImageView ocupar uma porcentagem maior da tela
- [x] Adicionar Label com propriedade Wrap para miniBio do artista
- [x] Reduzir espessura das bordas ou utilizar outra cor

**Comment by Joao-Pedro-P-Holanda** [comment]
Task finalizada
